# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DEV Maytok
email: khan@maytok.com
description: "Apuntes sobre desarrollo y tecnología en general."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dev.maytok.com" # the base hostname & protocol for your site
twitter_username: sakyastelios
github_username:  SakyaStelios
paginate: 5
permalink: pretty
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
